### ISSUE TITLE
怎么使用呢？

### ISSUE THREAD

**Issue by ben1226q** [zjyl1994/securetunnel#1]
可以完善下怎么使用吗？
服务器端怎么使用，客户端怎么使用，完善下？

**Comment by zjyl1994** [comment]
以代码中的配置文件为例子，你需要先分别编译客户端和服务端。然后改写代码中的config.json，server_addr是服务器对外的接口，local_addr是对内服务的接口。
如果你是给mysql用，可以设置local_addr为127.0.0.1:3306,填好你自己服务端的地址，然后分别启动服务端和客户端。然后你使用mysql客户端连接本地的3306就可以访问到服务器上的3306了，中间的是使用配置文件中key加密的aes链接。
如果你是科学上网，和mysql基本一致，唯一的不同就是需要在服务器上准备一个socks5或者http代理的服务器，然后设置服务器上config.json的local_addr为代理的地址即可。（科学上网性能不佳，有时间我会优化的）

**Comment by ben1226q** [comment]
好的，我试试。
